/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\Users\rehya\OneDrive\Documents\Prjojects\3dmodel\3d\public\Car.glb 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2022-tushek-ts-900-racer-pro-gaming-1f342663b55b4a67a16685caf46f71f7
Title: 2022 Tushek TS 900 Racer Pro (Gaming)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Car.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartiled_carbon_chassis_UV1_Untitled_027_Default_Carbon_0.geometry} material={materials.Carbon} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartiled_carbon_chassis_UV1_Untitled_027_Default_Carpaint_0.geometry} material={materials.Carpaint} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_black_chassis_UV1_Untitled_015_Default_color_2_0.geometry} material={materials.color_2} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_black_chassis_UV1_Untitled_015_Default_Color_3_0.geometry} material={materials.Color_3} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_chassis_UV1_Untitled_002_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_chassis_UV1_Untitled_002_Default_geom_0.geometry} material={materials.geom} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelFR_UV1_Untitled_035_Default_Rim_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelFR_UV1_Untitled_035_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelFL_UV1_Untitled_047_Default_Rim_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelFL_UV1_Untitled_047_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelBR_UV1_Untitled_042_Default_Rim_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelBR_UV1_Untitled_042_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} />
        </group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelBL_UV1_Untitled_040_Default_Rim_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_wheelBL_UV1_Untitled_040_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} />
        </group>
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carglass_glass_UV1_Untitled_046_Default_glass_0.geometry} material={materials.glass} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartiled_carbon_detach_wing_10_UV1_Untitled_033_Default_color_2_0.geometry} material={materials.color_2} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_black_detach_wing_10_UV1_Untitled_018_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_detach_wing_10_UV1_Untitled_019_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_black_detach_trunk_10_UV1_Untitled_017_Default_color_2_0.geometry} material={materials.color_2} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carlicenseplate_chassis_UV1_Untitled_016_Default_Plate_0.geometry} material={materials.Plate} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_caremissive_ID_rear_chassis_UV2_Untitled_009_Default_emis_0.geometry} material={materials.emis} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartiled_grids_chassis_UV1_Untitled_001_Default_grid_0.geometry} material={materials.grid} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carunderside_chassis_UV1_Untitled_044_Default_under_0.geometry} material={materials.under} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_custom02_chassis_UV1_Untitled_023_Default_Carpaint_0.geometry} material={materials.Carpaint} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcarpaint_chassis_UV1_Untitled_014_Default_Carpaint_0.geometry} material={materials.Carpaint} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_normal_chassis_UV2_Untitled_006_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcalipers_garage_wheelFR_caliper_UV1_Untitled_030_Default_Calipers_0.geometry} material={materials.Calipers} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_tiled_carbon_wheelFR_UV1_Untitled_045_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartires_wheelFR_tire_UV1_Untitled_013_Default_tire_0.geometry} material={materials.tire} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_normal_wheelFR_tire_UV2_Untitled_022_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcalipers_garage_wheelFL_caliper_UV1_Untitled_029_Default_Calipers_0.geometry} material={materials.Calipers} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartires_wheelFL_tire_UV1_Untitled_008_Default_tire_0.geometry} material={materials.tire} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_normal_wheelFL_tire_UV2_Untitled_012_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_tiled_carbon_wheelFL_UV1_Untitled_036_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcalipers_garage_wheelBR_caliper_UV1_Untitled_028_Default_Calipers_0.geometry} material={materials.Calipers} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartires_wheelBR_tire_UV1_Untitled_024_Default_tire_0.geometry} material={materials.tire} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_normal_wheelBR_tire_UV2_Untitled_010_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_tiled_carbon_wheelBR_UV1_Untitled_034_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carrims_tiled_carbon_wheelBL_UV1_Untitled_031_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartires_wheelBL_tire_UV1_Untitled_007_Default_tire_0.geometry} material={materials.tire} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_normal_wheelBL_tire_UV2_Untitled_021_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_carcalipers_garage_wheelBL_caliper_UV1_Untitled_025_Default_Calipers_0.geometry} material={materials.Calipers} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cartiled_carbon_steering_wheel_UV1_Untitled_038_Default_Carbon_0.geometry} material={materials.Carbon} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Tushek_TS_900_H_APEX_cardetails_steering_wheel_UV1_Untitled_020_Default_Tushek_TS_900_H_APEX_carDefault1_0.geometry} material={materials.Tushek_TS_900_H_APEX_carDefault1} rotation={[-Math.PI, 0, -Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Car.glb')
